#!/bin/bash
if [ "$1" != "" ]; then
  echo "Copying server"
  mkdir -p deploy
  cp server/package.json deploy
  cp server/app.js deploy
  cp server/*.enc deploy
  cp server/crypto/ebs.env deploy/.env
  cd deploy
  npm install
  cd ..
  echo "=> Building React.."
  npm install
  npm run build
  echo "=> Removing build folder..."
  rm -rf deploy/build
  mv build deploy
  echo "=> Zipping..."
  cd deploy
  mkdir -p ebs
  zip -r ebs/hdc.$1.zip *.js *.json *.yaml *.enc .env .ebextensions/* build/* node_modules/*
  echo "=> Done"
  cd ..
else
  echo "=> Provide version number (x.y.z) to build for elastic beanstalk"
fi